version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Start
          command: bash earthquake.sh 2019-12-10 2019-12-15 Barberino
